# Generated by Django 4.1.3 on 2022-11-13 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DashR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_spend', models.IntegerField(default=0)),
                ('invoice_value', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='invoice',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='DashR.invoice'),
            preserve_default=False,
        ),
    ]
