# Generated by Django 4.1.3 on 2022-11-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashR', '0002_invoice_project_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='dev',
            name='firstname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dev',
            name='lastname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
