# Generated by Django 4.1.3 on 2022-12-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashR', '0004_rename_price_per_hour_dev_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isOver',
            field=models.BooleanField(default=False),
        ),
    ]
